version: '3.1'

services:

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5004:5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend

  fe:
    stdin_open: true
    build:
      context: ./fe
      dockerfile: Dockerfile
    # ~dk same problem here..
    #volumes:
      #- './fe:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - 3007:80
    environment:
      - NODE_ENV=development
      - REACT_APP_BE_NETWORK=backend
      - REACT_APP_BE_PORT=5000
      - REACT_APP_API_SERVICE_URL=backend:5000
    depends_on:
      - be
    # specifies frontend and backend as the networks the fe service will have access to
    networks:
      - frontend
      - backend
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend
      
# bridge networks to allow the containers to communicate with each other
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
